tap 'caskroom/cask'
tap 'homebrew/bundle'

cask 'alfred'
cask 'sequel-pro'
cask 'visual-studio-code'
cask 'macdown'
cask 'tower'
cask 'jetbrains-toolbox'
cask 'docker'
cask 'google-chrome'
cask 'discord'
cask 'steam'
cask 'mactex'

